"""Authenticated, bounded Evidence ingestion; only the server holds DB credentials."""

from hashlib import sha256
import hmac
import json
import re
from typing import Any, Literal
import zlib

from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, ValidationError, model_validator
from starlette.concurrency import run_in_threadpool
from supabase import Client, create_client

from .config import Settings
from .evidence_security import (
    ARTIFACT_FILENAMES, parse_finite_float, redact, redact_artifact, validate_json_value,
)


EVENT_REQUEST_LIMIT = 8 * 1024 * 1024
ARTIFACT_REQUEST_LIMIT = 32 * 1024 * 1024
EVENT_BATCH_LIMIT = 250
ARTIFACT_BUCKET = "os-agent-evidence"
IDENTIFIER_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$"
EVENT_ID_PATTERN = r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,255}$"
_IDENTIFIER = re.compile(IDENTIFIER_PATTERN)
_EVENT_ID = re.compile(EVENT_ID_PATTERN)
_SHA256 = re.compile(r"^[0-9a-f]{64}$")


class EvidenceContext(BaseModel):
    model_config = ConfigDict(extra="forbid")

    run_id: str | None = Field(default=None, pattern=IDENTIFIER_PATTERN)
    action_id: str | None = Field(default=None, pattern=IDENTIFIER_PATTERN)
    step_id: str | None = Field(default=None, max_length=256)
    tool_call_id: str | None = Field(default=None, max_length=256)


class EvidenceEvent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["os-agent-evidence-v1"]
    event_id: str = Field(pattern=EVENT_ID_PATTERN)
    source_type: Literal[
        "auditd", "journald", "docker_log", "docker_event", "executor", "snapshot", "unknown"
    ]
    source: str = Field(min_length=1, max_length=512)
    event_type: str = Field(min_length=1, max_length=256)
    occurred_at: AwareDatetime
    collector_received_at: AwareDatetime
    environment_id: str = Field(pattern=IDENTIFIER_PATTERN)
    topology_revision: str = Field(min_length=1, max_length=256)
    message: str
    collector: dict[str, Any]
    payload: dict[str, Any]
    # Omitted fields are accepted for already-buffered stage-1 v1 events. No
    # context is guessed from free-form messages or time proximity.
    context: EvidenceContext = Field(default_factory=EvidenceContext)
    status: Literal["ok", "parse_error", "collection_error"] = "ok"

    @model_validator(mode="before")
    @classmethod
    def preserve_buffered_error_flags(cls, value: Any) -> Any:
        # JSONB cannot represent NUL or lone Unicode surrogates. Validate keys
        # and values before masking, as well as nested non-finite numbers, so
        # invalid input gets a permanent safe 422 instead of endless 503 retry.
        validate_json_value(value, reject_nul=True)
        if isinstance(value, dict) and "status" not in value:
            payload = value.get("payload")
            if isinstance(payload, dict):
                if payload.get("collection_error"):
                    return {**value, "status": "collection_error"}
                if payload.get("parse_error"):
                    return {**value, "status": "parse_error"}
        return value


class EvidenceConflict(Exception):
    """A previous immutable artifact reference disagrees with this request."""


class SupabaseEvidenceRepository:
    """Strict persistence: failures propagate, and never fall back to memory."""

    def __init__(self, url: str, secret_key: str, client: Client | None = None) -> None:
        self._client = client or create_client(url, secret_key)

    def save_events(self, events: list[EvidenceEvent]) -> None:
        self._client.table("evidence_events").upsert(
            [event.model_dump(mode="json") for event in events],
            on_conflict="environment_id,event_id",
            ignore_duplicates=True,
        ).execute()

    def save_artifact(self, metadata: dict[str, Any], data: bytes) -> dict[str, Any]:
        # Never upload into an accidentally public bucket. No public/signed URL
        # is generated by this API; consumers receive an opaque private key.
        bucket = self._client.storage.get_bucket(ARTIFACT_BUCKET)
        is_public = bucket.get("public") if isinstance(bucket, dict) else getattr(bucket, "public", None)
        if is_public is not False:
            raise RuntimeError("Evidence artifact bucket must be private")
        content_type = "application/json" if metadata["filename"].endswith(".json") else "text/plain; charset=utf-8"
        self._client.storage.from_(ARTIFACT_BUCKET).upload(
            metadata["object_path"],
            data,
            file_options={"content-type": content_type, "upsert": "true", "cache-control": "0"},
        )
        # A deterministic content-addressed path makes a retry safe even if
        # Storage succeeded but this DB write failed on the previous attempt.
        self._client.table("evidence_artifacts").upsert(
            metadata,
            on_conflict="environment_id,event_id,filename",
            ignore_duplicates=True,
        ).execute()
        result = (
            self._client.table("evidence_artifacts")
            .select("*")
            .eq("environment_id", metadata["environment_id"])
            .eq("event_id", metadata["event_id"])
            .eq("filename", metadata["filename"])
            .limit(1)
            .execute()
        )
        if not result.data:
            raise RuntimeError("Artifact metadata was not persisted")
        stored = result.data[0]
        if any(stored.get(key) != value for key, value in metadata.items()):
            raise EvidenceConflict("Artifact reference already exists")
        return {key: stored[key] for key in (
            "event_id", "filename", "bucket", "object_path", "size_bytes",
            "sha256", "original_sha256", "status",
        )}


def _reject_constant(_value: str) -> None:
    raise ValueError("Non-finite JSON number")


async def _read_bounded_body(request: Request, limit: int, *, gzip_allowed: bool) -> bytes:
    encoding = request.headers.get("content-encoding", "identity").strip().lower()
    if encoding not in ("identity", "gzip") or (encoding == "gzip" and not gzip_allowed):
        raise HTTPException(status_code=415, detail="Unsupported content encoding")
    content_length = request.headers.get("content-length")
    if content_length is not None:
        try:
            size = int(content_length)
        except ValueError:
            raise HTTPException(status_code=400, detail="Invalid content length") from None
        if size < 0:
            raise HTTPException(status_code=400, detail="Invalid content length")
        if size > limit:
            raise HTTPException(status_code=413, detail="Evidence request is too large")
    decoder = zlib.decompressobj(16 + zlib.MAX_WBITS) if encoding == "gzip" else None
    raw_size = 0
    output = bytearray()
    try:
        async for chunk in request.stream():
            raw_size += len(chunk)
            if raw_size > limit:
                raise HTTPException(status_code=413, detail="Evidence request is too large")
            if decoder is None:
                output.extend(chunk)
            else:
                output.extend(decoder.decompress(chunk, limit - len(output) + 1))
                if decoder.unused_data:
                    raise HTTPException(status_code=400, detail="Invalid gzip body")
            if len(output) > limit:
                raise HTTPException(status_code=413, detail="Evidence request is too large")
        if decoder is not None and not decoder.eof:
            raise HTTPException(status_code=400, detail="Invalid gzip body")
    except zlib.error:
        raise HTTPException(status_code=400, detail="Invalid gzip body") from None
    return bytes(output)


def create_evidence_router(
    settings: Settings,
    repository: SupabaseEvidenceRepository | None = None,
) -> APIRouter:
    router = APIRouter(prefix="/internal/evidence", tags=["internal-evidence"])
    active_repository = repository
    if (
        active_repository is None and settings.evidence_collector_token
        and settings.supabase_url and settings.supabase_secret_key
    ):
        active_repository = SupabaseEvidenceRepository(settings.supabase_url, settings.supabase_secret_key)

    def authenticate(request: Request) -> SupabaseEvidenceRepository:
        token = settings.evidence_collector_token
        if not token:
            raise HTTPException(status_code=503, detail="Evidence ingestion is not configured")
        scheme, separator, supplied = request.headers.get("authorization", "").partition(" ")
        if (
            not separator or scheme.lower() != "bearer"
            or not hmac.compare_digest(supplied.encode("utf-8"), token.encode("utf-8"))
        ):
            raise HTTPException(
                status_code=401, detail="Invalid collector credentials",
                headers={"WWW-Authenticate": "Bearer"},
            )
        if active_repository is None:
            raise HTTPException(status_code=503, detail="Evidence storage is not configured")
        return active_repository

    @router.head("/events")
    async def healthcheck(request: Request) -> Response:
        authenticate(request)
        return Response(status_code=200)

    @router.post("/events")
    async def receive_events(request: Request) -> dict[str, int]:
        target = authenticate(request)
        if request.headers.get("content-type", "").split(";", 1)[0].strip().lower() != "application/x-ndjson":
            raise HTTPException(status_code=415, detail="Expected application/x-ndjson")
        body = await _read_bounded_body(request, EVENT_REQUEST_LIMIT, gzip_allowed=True)
        lines = [line for line in body.split(b"\n") if line.strip()]
        if not lines or len(lines) > EVENT_BATCH_LIMIT:
            raise HTTPException(status_code=422, detail="Invalid Evidence batch size")
        try:
            # Validate all records before issuing one DB operation. Revalidate
            # the sanitized envelope so a malformed identifier cannot bypass
            # schema checks through a redaction replacement.
            events = [
                EvidenceEvent.model_validate(redact(
                    EvidenceEvent.model_validate(
                        json.loads(
                            line.decode("utf-8"), parse_constant=_reject_constant,
                            parse_float=parse_finite_float,
                        )
                    ).model_dump(mode="json")
                ))
                for line in lines
            ]
        except (ValueError, ValidationError, UnicodeError, RecursionError):
            # ValidationError.errors() includes the raw input by default.
            raise HTTPException(status_code=422, detail="Invalid Evidence event") from None
        try:
            await run_in_threadpool(target.save_events, events)
        except Exception:
            raise HTTPException(status_code=503, detail="Evidence persistence failed; retry this batch") from None
        return {"accepted": len(events)}

    @router.put("/artifacts/{run_id}/{action_id}/{phase}/{filename}")
    async def receive_artifact(
        run_id: str, action_id: str, phase: str, filename: str, request: Request,
    ) -> dict[str, Any]:
        target = authenticate(request)
        environment_id = request.headers.get("x-evidence-environment-id", "")
        event_id = request.headers.get("x-evidence-event-id", "")
        transmitted_sha = request.headers.get("x-evidence-sha256", "")
        original_sha = request.headers.get("x-evidence-original-sha256", "")
        if (
            not all(_IDENTIFIER.fullmatch(value) for value in (run_id, action_id, environment_id))
            or not _EVENT_ID.fullmatch(event_id) or phase not in ("before", "after")
            or filename not in ARTIFACT_FILENAMES
            or not _SHA256.fullmatch(transmitted_sha) or not _SHA256.fullmatch(original_sha)
        ):
            raise HTTPException(status_code=422, detail="Invalid Evidence artifact metadata")
        if request.headers.get("content-type", "").split(";", 1)[0].strip().lower() != "application/octet-stream":
            raise HTTPException(status_code=415, detail="Expected application/octet-stream")
        body = await _read_bounded_body(request, ARTIFACT_REQUEST_LIMIT, gzip_allowed=False)
        if not hmac.compare_digest(sha256(body).hexdigest(), transmitted_sha):
            raise HTTPException(status_code=422, detail="Evidence artifact hash mismatch")
        try:
            stored_body = redact_artifact(body, filename)
        except (ValueError, UnicodeError, RecursionError):
            raise HTTPException(status_code=422, detail="Invalid Evidence artifact content") from None
        if len(stored_body) > ARTIFACT_REQUEST_LIMIT:
            raise HTTPException(status_code=413, detail="Evidence artifact is too large")
        stored_sha = sha256(stored_body).hexdigest()
        metadata = {
            "environment_id": environment_id, "event_id": event_id,
            "run_id": run_id, "action_id": action_id, "phase": phase,
            "filename": filename, "bucket": ARTIFACT_BUCKET,
            "object_path": f"{environment_id}/{run_id}/{action_id}/{phase}/{event_id}/{stored_sha}/{filename}",
            "size_bytes": len(stored_body), "sha256": stored_sha,
            "original_sha256": original_sha, "status": "uploaded",
        }
        try:
            return await run_in_threadpool(target.save_artifact, metadata, stored_body)
        except EvidenceConflict:
            raise HTTPException(status_code=409, detail="Evidence artifact reference already exists") from None
        except Exception:
            raise HTTPException(status_code=503, detail="Evidence artifact persistence failed; retry this file") from None

    return router
